### PR TITLE
Twig 2 support

### PR DESCRIPTION
**Pull request by damienflament**
This is a simple Twig 2 support.
Maybe some refactoring is necessary to follow Twig 2 conventions.

Twig 2 require PHP 7, but supporting it will be necessary to allow symfony-cmf/create-bundle to support Symfony 3.

### CODE REVIEW

**Comment by dbu** [comment]
how hard would it be to support both twig 1 and 2? even symfony master still allows twig version 1...

**Comment by dbu** [comment]
oh, and this was meant as an actual question, not demeaning. just noticed it might come across wrongly ;-)

**Comment by damienflament** [comment]
I don't know Symfony support both Twig 1 and 2.
I will check.

**Comment by damienflament** [comment]
@dbu : It seems to be OK.

Finally, the only change made to support Twig 1.x was to use [Twig_SimpleFunction](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/SimpleFunction.php) which is an empty class extending Twig_Function. It's not marked as deprecated but is explicitly documented as allowing Twig 1.x compatibility.

**Comment by dbu** [comment]
great! i think this is more convenient for users. glad it works without any version checks! i let @flack review and merge.

**Comment by dbu** [comment]
great! i think this is more convenient for users. glad it works without any version checks! i let @flack review and merge.

**Comment by flack** [comment]
I don't really use Twig myself, so I'm not overly qualified to review this :-)

But the diff looks fine, so I'll merge as-is. Thanks @damienflament !

Should we tag a release based on this? Twig 2 support seems like it could be interesting to quite a few peopl

**Pull request merged**
